In [1]:
push!(LOAD_PATH, ".")
using Power
using Traffic
using Hydrogen
using JLD

In [2]:
##########################################
# info
##########################################
# HRS connect to grid bus number
HRS_bus = [2, 5, 8, 9, 12, 16, 18, 21] 
# HRS location is stored in "Traffic.jl"

# power factor of electrolyser
power_factor = 0.95
QP_ratio = sqrt(1-power_factor^2) / power_factor;

In [3]:
# initial value for iteration
T = 24
# 1. TA and LMP 
# the initial power of electrolyser is 0
# the initial price of hydrogen is average price ($10)
ρⱼ = 10 * ones((Nₕ, T))
pᵈʰ = 0 * ones((length(bus), T))
pᵈʰ[HRS_bus, :] = zeros((Nₕ, T))
qᵈʰ = QP_ratio * pᵈʰ;

record_ρⱼ = []
record_pᵈ = []
record_λⱼ = []
record_hydrogen_demand = []
record_true_ρⱼ = []

# save path 
output_path = "./result/record.jld"

# continue from the last run
if isfile(output_path)
    last_run = load(output_path)
    # get the last results
    record_ρⱼ = last_run["record_ρⱼ"]
    record_pᵈ = last_run["record_pᵈ"]
    record_λⱼ = last_run["record_λⱼ"]
    record_true_ρⱼ = last_run["record_true_ρⱼ"]
    record_hydrogen_demand = last_run["record_hydrogen_demand"]
    ρⱼ = last_run["record_ρⱼ"][end]
    pᵈ = last_run["record_pᵈ"][end]
    λⱼ = last_run["record_λⱼ"][end]
    hydrogen_demand = last_run["record_hydrogen_demand"][end]
    # rearrange pᵈʰ, qᵈʰ, ρⱼ
    pᵈʰ = 0 * ones((length(bus), T))
    pᵈʰ[HRS_bus, :] = pᵈ  # assign power to bus
    qᵈʰ = QP_ratio * pᵈʰ  # assign power to bus
end

In [4]:
N = 1000
for n in 1:N
    # true iteration times
    iter_n = length(record_ρⱼ) + 1
    
    # T single-period TA and LMP problem
    λⱼ = zeros((Nₕ, T))
    hydrogen_demand = zeros((Nₕ, T))
    for t = 1:T
        println("------------------------------------------------")
        println("n=$n, iter_n=$iter_n, t=$t start")
        λⱼ[:, t] = solve_LMP(pᵈᵗAllTime[:,t], qᵈᵗAllTime[:,t], pᵈʰ[:,t], qᵈʰ[:,t])[HRS_bus]
        hydrogen_demand[:, t] = solve_TA(ρⱼ, qᵍALLTime[t], qʰALLTime[t])
        println("n=$n, iter_n=$iter_n, t=$t finish")
        println("------------------------------------------------")
    end

    # multi-period HRS operation problem
    HRS_result = solve_HRS_op(λⱼ, hydrogen_demand)

    # rearrange pᵈʰ, qᵈʰ, ρⱼ
    pᵈʰ = 0 * ones((length(bus), T))
    pᵈʰ[HRS_bus, :] = HRS_result.pᵈ  # assign power to bus
    qᵈʰ = QP_ratio * pᵈʰ  # assign power to bus
    # inertial hydrogen price
    if length(record_ρⱼ) > 1
        factor = 0.1
        ρⱼ = record_ρⱼ[end]  + factor * (HRS_result.ρⱼ - record_ρⱼ[end])
    else
        ρⱼ = HRS_result.ρⱼ
    end
    
    # record all variabels
    push!(record_pᵈ, HRS_result.pᵈ)
    push!(record_true_ρⱼ, HRS_result.ρⱼ)
    push!(record_ρⱼ, ρⱼ)
    push!(record_λⱼ, λⱼ)
    push!(record_hydrogen_demand, hydrogen_demand)

    # save variables
    save(output_path, "record_ρⱼ", record_ρⱼ, "record_pᵈ", record_pᵈ, 
        "record_λⱼ", record_λⱼ, "record_hydrogen_demand", record_hydrogen_demand,
        "record_true_ρⱼ", record_true_ρⱼ
    )

    # exit condition
    if length(record_hydrogen_demand) > 1
        # absolute errors
        error_ρⱼ = sum(abs.(record_ρⱼ[end] - record_ρⱼ[end-1]))
        error_pᵈ = sum(abs.(record_pᵈ[end] - record_pᵈ[end-1]))
        error_λⱼ = sum(abs.(record_λⱼ[end] - record_λⱼ[end-1]))
        error_hydrogen_demand = sum(abs.(record_hydrogen_demand[end] - record_hydrogen_demand[end-1]))
        error = error_ρⱼ + error_pᵈ + error_λⱼ + error_hydrogen_demand
        println("*********")
        println("n=$n, iter_n=$iter_n")
        println("Error: $error")
        println("- error_ρⱼ: $error_ρⱼ") 
        println("- error_pᵈ: $error_pᵈ") 
        println("- error_λⱼ: $error_λⱼ")
        println("- error_hydrogen_demand: $error_hydrogen_demand")
        println("*********")
        
        # relative errors
        error_ρⱼ = sum(abs.(record_ρⱼ[end] - record_ρⱼ[end-1])) / sum(abs.(record_ρⱼ[end]))
        error_pᵈ = sum(abs.(record_pᵈ[end] - record_pᵈ[end-1]))  / sum(abs.(record_pᵈ[end]))
        error_λⱼ = sum(abs.(record_λⱼ[end] - record_λⱼ[end-1]))  / sum(abs.(record_λⱼ[end]))
        error_hydrogen_demand = sum(abs.(record_hydrogen_demand[end] - record_hydrogen_demand[end-1]))  / sum(abs.(record_hydrogen_demand[end]))
        error = error_ρⱼ + error_pᵈ + error_λⱼ + error_hydrogen_demand
        println("*********")
        println("n=$n, iter_n=$iter_n")
        println("Error: $error")
        println("- relative error_ρⱼ: $error_ρⱼ") 
        println("- relative error_pᵈ: $error_pᵈ") 
        println("- relative error_λⱼ: $error_λⱼ")
        println("- relative error_hydrogen_demand: $error_hydrogen_demand")
        println("*********")
        
        # exit condition for relative errors
        if error_ρⱼ < 1e-5 && error_pᵈ < 1e-2 && error_λⱼ < 1e-5 && error_hydrogen_demand < 1e-5
            println("Converged!")
            break
        end
    end
end


------------------------------------------------
n=1, iter_n=1, t=1 start
Academic license - for non-commercial use only
【Power Result】:Model was solved to optimality (subject to tolerances), and an optimal solution is available.

******************************************************************************
This program contains Ipopt, a library for large-scale nonlinear optimization.
 Ipopt is released as open source code under the Eclipse Public License (EPL).
         For more information visit https://github.com/coin-or/Ipopt
******************************************************************************

【Traffic Result】:Solve_Succeeded
n=1, iter_n=1, t=1 finish
------------------------------------------------
------------------------------------------------
n=1, iter_n=1, t=2 start
Academic license - for non-commercial use only
【Power Result】:Model was solved to optimality (subject to tolerances), and an optimal solution is available.
【Traffic Result】:Solve_Succeeded
n=1, iter_n=

【Power Result】:Model was solved to optimality (subject to tolerances), and an optimal solution is available.
【Traffic Result】:Solve_Succeeded
n=1, iter_n=1, t=24 finish
------------------------------------------------


8×24 Matrix{Float64}:
  9.96408  9.95934   9.96408   9.972    …   9.97329   9.97902   9.97204
  9.9337   9.93659   9.93386   9.93232      9.93143   9.93067   9.93217
  9.93068  9.93633   9.93084   9.92247      9.91399   9.91541   9.9225
  9.99462  9.98222   9.99429  10.0108      10.052    10.0548   10.011
 10.0112   9.99908  10.0112   10.045       10.0622   10.046    10.045
  9.94209  9.93659   9.94225   9.93924  …   9.92714   9.92816   9.93908
 10.0051   9.99516  10.0051   10.0136      10.01     10.0034   10.0177
  9.98558  9.98561   9.98541   9.96674      9.96366   9.96432   9.96287

8×24 Matrix{Float64}:
 4.32686   3.44056e-9  5.29575     …  7.4281        1.87578     5.13179
 0.269406  4.00255     1.79888e-8     5.27318       3.62847e-8  3.35028
 0.134791  1.29087     1.49207        3.1422e-9     1.11244     2.91849
 5.69158   0.641067    7.02674        5.54541       7.96077     6.87409
 3.73026   6.7946      2.3803         6.00151      10.2692      5.69198
 0.644275  1.30255     4.70155     …  5.47654e-10   2.26964     3.65916
 3.46106   6.6193      2.11101        6.3693        8.36646     4.47394
 5.2876    3.49294     3.93032        1.59803       6.61909     2.02224

Academic license - for non-commercial use only
【Hydrogen Result】:Model was solved to optimality (subject to tolerances), and an optimal solution is available.
Solution is optimal
------------------------------------------------
n=2, iter_n=2, t=1 start
Academic license - for non-commercial use only
【Power Result】:Model was solved to optimality (subject to tolerances), and an optimal solution is available.
【Traffic Result】:Solve_Succeeded
n=2, iter_n=2, t=1 finish
------------------------------------------------
------------------------------------------------
n=2, iter_n=2, t=2 start
Academic license - for non-commercial use only
【Power Result】:Model was solved to optimality (subject to tolerances), and an optimal solution is available.
【Traffic Result】:Solve_Succeeded
n=2, iter_n=2, t=2 finish
------------------------------------------------
------------------------------------------------
n=2, iter_n=2, t=3 start
Academic license - for non-commercial use only
【Power Result】:Model was

8×24 Matrix{Float64}:
  9.97959   9.97494   9.97958  10.0029   …   9.99644  10.0171   10.0029
  9.94919   9.95308   9.94935   9.94817      9.96509   9.96429   9.94799
  9.95052   9.95361   9.95068   9.94618      9.93298   9.93683   9.946
  9.98989   9.98374   9.98955   9.99849     10.0227   10.0158    9.9989
 10.0163   10.0084   10.0163   10.0273      10.0672   10.0462   10.0273
  9.95151   9.95548   9.95167   9.94638  …   9.92489   9.92791   9.9462
 10.013    10.0085   10.013    10.0104      10.0174   10.0089   10.0104
  9.9957    9.9924    9.99553   9.98516      9.97141   9.97069   9.98538

8×24 Matrix{Float64}:
 4.5816    3.65311e-9  5.69652      4.79259  …  8.0947      3.18365   6.14259
 0.549658  4.20699     2.49656e-10  4.30323     6.7211      0.868279  3.73758
 0.607885  1.53035     1.96516      5.00916     4.41599e-9  2.27976   3.65044
 5.03286   0.150425    6.3683       1.90088     3.84675     5.82351   5.96831
 3.49012   6.63102     2.14012      8.56438     5.79637     9.8566    4.51438
 0.651553  1.61213     4.70883      1.60247  …  7.2781e-10  1.53437   3.65916
 3.34455   6.63686     1.99455      7.82371     6.31412     8.22281   3.77371
 5.2876    3.23009     3.93032      1.31706     1.59803     6.54893   2.67577


【Traffic Result】:Solve_Succeeded
n=2, iter_n=2, t=24 finish
------------------------------------------------
Academic license - for non-commercial use only
【Hydrogen Result】:Model was solved to optimality (subject to tolerances), and an optimal solution is available.
Solution is optimal
*********
n=2, iter_n=2
Error: 2159.7118002322404
- error_ρⱼ: 3.011479755297634
- error_pᵈ: 161.2840949287306
- error_λⱼ: 117.37622187445237
- error_hydrogen_demand: 1878.0400036737597
*********
*********
n=2, iter_n=2
Error: 0.3343253038554074
- relative error_ρⱼ: 0.001570868920009908
- relative error_pᵈ: 0.19353535009085163
- relative error_λⱼ: 0.0040040917891288625
- relative error_hydrogen_demand: 0.13521499305541695
*********
------------------------------------------------
n=3, iter_n=3, t=1 start
Academic license - for non-commercial use only
【Power Result】:Model was solved to optimality (subject to tolerances), and an optimal solution is available.
【Traffic Result】:Solve_Succeeded
n=3, iter_n=3

【Power Result】:Model was solved to optimality (subject to tolerances), and an optimal solution is available.
【Traffic Result】:Solve_Succeeded
n=3, iter_n=3, t=23 finish
------------------------------------------------
------------------------------------------------
n=3, iter_n=3, t=24 start
Academic license - for non-commercial use only
【Power Result】:Model was solved to optimality (subject to tolerances), and an optimal solution is available.


8×24 Matrix{Float64}:
  9.98081   9.97639   9.98076   9.99616  …   9.99628  10.0113    9.99503
  9.95247   9.956     9.9535    9.95147      9.96705   9.9663    9.95127
  9.94999   9.9565    9.95133   9.94851      9.93688   9.9407    9.94942
  9.99042   9.98459   9.99005  10.0052      10.0208   10.0186   10.0056
 10.0157   10.0076   10.0156   10.0253      10.0625   10.0427   10.0253
  9.95464   9.95824   9.95474   9.94981  …   9.92957   9.93238   9.9496
 10.015    10.0077   10.0128   10.0027      10.0158   10.0079   10.0026
  9.99584   9.99267   9.99563   9.99338      9.97295   9.97227   9.99355

8×24 Matrix{Float64}:
 4.5816    2.86912e-9  5.69652      …  5.3947       5.68318   5.79404
 0.549658  4.20699     2.11898e-10     6.7211       0.868279  3.73758
 0.433204  1.53035     1.84871         3.95701e-9   2.26868   3.65044
 5.03286   0.150425    6.3683          3.84675      6.02397   6.29072
 3.51923   6.63102     2.16923         5.80745      9.8566    4.51438
 0.651553  1.61213     4.70883      …  6.52655e-10  1.53437   3.65916
 3.49012   6.63686     2.03822         6.31412      8.22281   3.4513
 5.2876    3.23009     3.93032         1.59803      6.54893   3.02432

【Traffic Result】:Solve_Succeeded
n=3, iter_n=3, t=24 finish
------------------------------------------------
Academic license - for non-commercial use only
【Hydrogen Result】:Model was solved to optimality (subject to tolerances), and an optimal solution is available.
Solution is optimal
*********
n=3, iter_n=3
Error: 279.2338958735508
- error_ρⱼ: 0.056868529325873496
- error_pᵈ: 43.775326610859764
- error_λⱼ: 23.13943738307603
- error_hydrogen_demand: 212.26226335028915
*********
*********
n=3, iter_n=3
Error: 0.06863090226928939
- relative error_ρⱼ: 2.966395002239353e-5
- relative error_pᵈ: 0.052528881788734855
- relative error_λⱼ: 0.0007899129218022132
- relative error_hydrogen_demand: 0.015282443608729924
*********
------------------------------------------------
n=4, iter_n=4, t=1 start
Academic license - for non-commercial use only
【Power Result】:Model was solved to optimality (subject to tolerances), and an optimal solution is available.
【Traffic Result】:Solve_Succeeded
n=4, iter

【Power Result】:Model was solved to optimality (subject to tolerances), and an optimal solution is available.
【Traffic Result】:Solve_Succeeded
n=4, iter_n=4, t=23 finish
------------------------------------------------
------------------------------------------------
n=4, iter_n=4, t=24 start
Academic license - for non-commercial use only
【Power Result】:Model was solved to optimality (subject to tolerances), and an optimal solution is available.


8×24 Matrix{Float64}:
  9.98574   9.98256   9.98567   9.99612  …   9.99751  10.0083    9.99613
  9.96532   9.96788   9.96536   9.96473      9.97645   9.97584   9.96461
  9.96353   9.96823   9.96514   9.96339      9.95471   9.9574    9.96327
  9.99266   9.98847   9.99236  10.0035      10.0152   10.0135   10.0037
 10.0108   10.005    10.0108   10.0179      10.0452   10.0308   10.0179
  9.96688   9.96949   9.96692   9.96352  …   9.94945   9.95141   9.96341
 10.0104   10.0051   10.0088   10.0016      10.0116   10.0058   10.0016
  9.99656   9.99429   9.99638   9.99492      9.9807    9.98014   9.99506

8×24 Matrix{Float64}:
 4.5816    1.39503e-9  5.69652      …  5.3947       5.68318   5.79404
 0.549658  4.20699     1.11272e-10     6.7211       0.868279  3.73758
 0.433204  1.53035     1.89238         1.92502e-9   2.26868   3.65044
 5.03286   0.150425    6.3683          3.84675      6.02397   6.29072
 3.51923   6.63102     2.16923         5.80745      9.8566    4.51438
 0.651553  1.61213     4.70883      …  3.14971e-10  1.53437   3.65916
 3.49012   6.63686     2.03822         6.31412      8.22281   3.4513
 5.2876    3.23009     3.93032         1.59803      6.54893   3.02432

【Traffic Result】:Solve_Succeeded
n=4, iter_n=4, t=24 finish
------------------------------------------------
Academic license - for non-commercial use only
【Hydrogen Result】:Model was solved to optimality (subject to tolerances), and an optimal solution is available.
Solution is optimal
*********
n=4, iter_n=4
Error: 15.055039287513228
- error_ρⱼ: 0.21118258328548478
- error_pᵈ: 6.372012026532325
- error_λⱼ: 2.074994167277282
- error_hydrogen_demand: 6.396850510418137
*********
*********
n=4, iter_n=4
Error: 0.008287737417753144
- relative error_ρⱼ: 0.00011015264263683104
- relative error_pᵈ: 0.007646194606073715
- relative error_λⱼ: 7.083017325203567e-5
- relative error_hydrogen_demand: 0.00046055999579056283
*********
------------------------------------------------
n=5, iter_n=5, t=1 start
Academic license - for non-commercial use only
【Power Result】:Model was solved to optimality (subject to tolerances), and an optimal solution is available.
【Traffic Result】:Solve_Succeeded
n=5, it

【Traffic Result】:Solve_Succeeded
n=5, iter_n=5, t=23 finish
------------------------------------------------
------------------------------------------------
n=5, iter_n=5, t=24 start
Academic license - for non-commercial use only
【Power Result】:Model was solved to optimality (subject to tolerances), and an optimal solution is available.

8×24 Matrix{Float64}:
  9.97894   9.97558   9.97886   9.99517  …   9.9963   10.0112    9.99415
  9.95149   9.95517   9.95157   9.95043      9.96703   9.96503   9.95033
  9.94901   9.95566   9.95126   9.94746      9.93682   9.94047   9.94847
  9.98948   9.98379   9.9891   10.0043      10.0208   10.0184   10.0047
 10.0148   10.0068   10.0147   10.0427      10.0626   10.0426   10.0244
  9.95366   9.95741   9.95374   9.94876  …   9.9295    9.93214   9.94866
 10.0151   10.0069   10.0128   10.0017      10.0159   10.0077   10.0018
  9.99491   9.99188   9.99468   9.97401      9.97293   9.97314   9.99266

8×24 Matrix{Float64}:
 4.53793   2.87697e-9  5.65285      …  5.3947       5.68318   5.79404
 0.549658  4.20699     2.29333e-10     6.7211       0.818163  3.73758
 0.433204  1.53035     1.89238         3.96725e-9   2.26868   3.65044
 5.03286   0.150425    6.3683          3.84675      6.02397   6.29072
 3.51923   6.63102     2.16923         5.80745      9.8566    4.51438
 0.651553  1.61213     4.70883      …  6.49119e-10  1.53437   3.65916
 3.53379   6.63686     2.08189         6.31412      8.22281   3.4513
 5.2876    3.23009     3.93032         1.59803      6.59904   3.02433


【Traffic Result】:Solve_Succeeded
n=5, iter_n=5, t=24 finish
------------------------------------------------
Academic license - for non-commercial use only
【Hydrogen Result】:Model was solved to optimality (subject to tolerances), and an optimal solution is available.
Solution is optimal
*********
n=5, iter_n=5
Error: 78.98845924558762
- error_ρⱼ: 0.038237860566692206
- error_pᵈ: 8.746982642763154
- error_λⱼ: 0.04287869826427482
- error_hydrogen_demand: 70.1603600439935
*********
*********
n=5, iter_n=5
Error: 0.015568886631396061
- relative error_ρⱼ: 1.994486874962004e-5
- relative error_pᵈ: 0.01049607740072709
- relative error_λⱼ: 1.4636705467245634e-6
- relative error_hydrogen_demand: 0.005051400691372627
*********
------------------------------------------------
n=6, iter_n=6, t=1 start
Academic license - for non-commercial use only
【Power Result】:Model was solved to optimality (subject to tolerances), and an optimal solution is available.
【Traffic Result】:Solve_Succeeded
n=6, iter

【Power Result】:Model was solved to optimality (subject to tolerances), and an optimal solution is available.
【Traffic Result】:Solve_Succeeded
n=6, iter_n=6, t=23 finish
------------------------------------------------
------------------------------------------------
n=6, iter_n=6, t=24 start
Academic license - for non-commercial use only
【Power Result】:Model was solved to optimality (subject to tolerances), and an optimal solution is available.

8×24 Matrix{Float64}:
  9.98213   9.97828   9.98206   9.99577  …   9.9967   10.0099    9.99487
  9.95687   9.96012   9.95694   9.95595      9.97065   9.96889   9.95587
  9.95466   9.96056   9.95667   9.95331      9.94377   9.94703   9.95422
  9.99068   9.98559   9.99034  10.0039      10.0185   10.0164   10.0043
 10.0132   10.0061   10.0131   10.0381      10.0557   10.0379   10.0218
  9.9588    9.96211   9.95887   9.95446  …   9.93725   9.93962   9.95438
 10.0126   10.0062   10.0106   10.0016      10.0141   10.0069   10.0016
  9.99551   9.99279   9.99531   9.97693      9.97591   9.97611   9.99355

8×24 Matrix{Float64}:
 4.5816    2.22752e-9  5.69652      …  5.3947       5.68318   5.79404
 0.549658  4.20699     1.77666e-10     6.7211       0.818163  3.73758
 0.433204  1.53035     1.89238         3.0723e-9    2.26868   3.65044
 5.03286   0.150425    6.3683          3.84675      6.02397   6.29072
 3.51923   6.63102     2.16923         5.80745      9.8566    4.51439
 0.651553  1.61213     4.70883      …  5.02912e-10  1.53437   3.65916
 3.49012   6.63686     2.03822         6.31412      8.22281   3.4513
 5.2876    3.23009     3.93032         1.59803      6.59904   3.02432


【Traffic Result】:Solve_Succeeded
n=6, iter_n=6, t=24 finish
------------------------------------------------
Academic license - for non-commercial use only
【Hydrogen Result】:Model was solved to optimality (subject to tolerances), and an optimal solution is available.
Solution is optimal
*********
n=6, iter_n=6
Error: 10.904043435280794
- error_ρⱼ: 0.08590522760392716
- error_pᵈ: 4.886741118981175
- error_λⱼ: 0.10838678548088865
- error_hydrogen_demand: 5.823010303214804
*********
*********
n=6, iter_n=6
Error: 0.0063316727491757275
- relative error_ρⱼ: 4.4807498710444346e-5
- relative error_pᵈ: 0.005863920766111406
- relative error_λⱼ: 3.699795016771962e-6
- relative error_hydrogen_demand: 0.0004192446893371045
*********
------------------------------------------------
n=7, iter_n=7, t=1 start
Academic license - for non-commercial use only
【Power Result】:Model was solved to optimality (subject to tolerances), and an optimal solution is available.
【Traffic Result】:Solve_Succeeded
n=7, 

【Power Result】:Model was solved to optimality (subject to tolerances), and an optimal solution is available.
【Traffic Result】:Solve_Succeeded
n=7, iter_n=7, t=23 finish
------------------------------------------------
------------------------------------------------
n=7, iter_n=7, t=24 start
Academic license - for non-commercial use only
【Power Result】:Model was solved to optimality (subject to tolerances), and an optimal solution is available.

8×24 Matrix{Float64}:
  9.98171   9.97778   9.98164   9.99562  …   9.99664  10.0101    9.9947
  9.956     9.95929   9.95607   9.95508      9.97012   9.9683    9.955
  9.95375   9.95974   9.95579   9.95239      9.94275   9.94605   9.95332
  9.99042   9.98522   9.99007  10.0039      10.0189   10.0167   10.0043
 10.0133   10.0061   10.0133   10.0387      10.0567   10.0385   10.0221
  9.95796   9.96132   9.95804   9.95357  …   9.93612   9.93851   9.95349
 10.0128   10.0062   10.0107   10.0015      10.0144   10.007    10.0016
  9.99534   9.99255   9.99513   9.97644      9.97547   9.97566   9.99335

8×24 Matrix{Float64}:
 4.5816    2.3201e-9  5.69652      …  5.3947       5.68318   5.79404
 0.549658  4.20699    1.84937e-10     6.7211       0.818163  3.73758
 0.433204  1.53035    1.89238         3.19786e-9   2.26868   3.65044
 5.03286   0.150425   6.3683          3.84675      6.02397   6.29072
 3.51923   6.63102    2.16923         5.80745      9.8566    4.51438
 0.651553  1.61213    4.70883      …  5.23464e-10  1.53437   3.65916
 3.49012   6.63686    2.03822         6.31412      8.22281   3.4513
 5.2876    3.23009    3.93032         1.59803      6.59904   3.02433


【Traffic Result】:Solve_Succeeded
n=7, iter_n=7, t=24 finish
------------------------------------------------
Academic license - for non-commercial use only
【Hydrogen Result】:Model was solved to optimality (subject to tolerances), and an optimal solution is available.
Solution is optimal
*********
n=7, iter_n=7
Error: 8.787899919725675
- error_ρⱼ: 0.06758365417252321
- error_pᵈ: 4.657662833660446
- error_λⱼ: 0.05297028568210749
- error_hydrogen_demand: 4.009683146210598
*********
*********
n=7, iter_n=7
Error: 0.005914782483112951
- relative error_ρⱼ: 3.525073149124262e-5
- relative error_pᵈ: 0.005589034715864309
- relative error_λⱼ: 1.808149024373466e-6
- relative error_hydrogen_demand: 0.0002886888867330256
*********
------------------------------------------------
n=8, iter_n=8, t=1 start
Academic license - for non-commercial use only
【Power Result】:Model was solved to optimality (subject to tolerances), and an optimal solution is available.
【Traffic Result】:Solve_Succeeded
n=8, ite

【Traffic Result】:Solve_Succeeded
n=8, iter_n=8, t=23 finish
------------------------------------------------
------------------------------------------------
n=8, iter_n=8, t=24 start
Academic license - for non-commercial use only
【Power Result】:Model was solved to optimality (subject to tolerances), and an optimal solution is available.

8×24 Matrix{Float64}:
  9.97913   9.9758    9.97912   9.99526  …   9.99637  10.0112    9.99693
  9.95184   9.95551   9.95199   9.95078      9.96727   9.9653    9.95079
  9.94937   9.956     9.94952   9.94783      9.93724   9.94088   9.94636
  9.98961   9.98396   9.9893   10.0043      10.0208   10.0184   10.0049
 10.0147   10.0069   10.0147   10.0425      10.0623   10.0424   10.0244
  9.954     9.95773   9.95415   9.94912  …   9.92997   9.9326    9.94913
 10.015    10.007    10.015    10.0017      10.0158   10.0078   10.0019
  9.99501   9.99201   9.99485   9.97422      9.97314   9.97336   9.99287

8×24 Matrix{Float64}:
 4.53793   2.83472e-9  5.65285      …  5.3947       5.68318   5.91603
 0.549658  4.20699     2.25958e-10     6.7211       0.818163  3.73758
 0.433204  1.53035     1.79048         3.90718e-9   2.26868   3.52845
 5.03286   0.150425    6.3683          3.84675      6.02397   6.29072
 3.51923   6.63102     2.16923         5.80745      9.8566    4.51438
 0.651553  1.61213     4.70883      …  6.39574e-10  1.53437   3.65916
 3.53379   6.63686     2.18379         6.31412      8.22281   3.4513
 5.2876    3.23009     3.93032         1.59803      6.59904   3.02433


【Traffic Result】:Solve_Succeeded
n=8, iter_n=8, t=24 finish
------------------------------------------------
Academic license - for non-commercial use only
【Hydrogen Result】:Model was solved to optimality (subject to tolerances), and an optimal solution is available.
Solution is optimal
*********
n=8, iter_n=8
Error: 74.15615124299926
- error_ρⱼ: 0.023547701026181755
- error_pᵈ: 8.361891241458874
- error_λⱼ: 0.023892228894538903
- error_hydrogen_demand: 65.74682007161967
*********
*********
n=8, iter_n=8
Error: 0.014780713700254362
- relative error_ρⱼ: 1.2282200836839918e-5
- relative error_pᵈ: 0.010033980991616977
- relative error_λⱼ: 8.155646405080908e-7
- relative error_hydrogen_demand: 0.0047336349431600375
*********
------------------------------------------------
n=9, iter_n=9, t=1 start
Academic license - for non-commercial use only
【Power Result】:Model was solved to optimality (subject to tolerances), and an optimal solution is available.
【Traffic Result】:Solve_Succeeded
n=9, 

【Traffic Result】:Solve_Succeeded
n=9, iter_n=9, t=23 finish
------------------------------------------------
------------------------------------------------
n=9, iter_n=9, t=24 start
Academic license - for non-commercial use only
【Power Result】:Model was solved to optimality (subject to tolerances), and an optimal solution is available.


8×24 Matrix{Float64}:
  9.9798    9.97549   9.97973   9.99534  …   9.99635  10.0115    9.99432
  9.95098   9.95476   9.95106   9.94989      9.96662   9.96465   9.94982
  9.94846   9.95527   9.95075   9.94687      9.93594   9.93971   9.94793
  9.98957   9.98384   9.98918  10.0046      10.0213   10.0189   10.0051
 10.0152   10.0072   10.0152   10.0436      10.0637   10.0434   10.0251
  9.95318   9.95704   9.95327   9.94819  …   9.92851   9.93125   9.94812
 10.0146   10.0073   10.0123   10.0019      10.0162   10.008    10.0021
  9.99508   9.99205   9.99485   9.97384      9.97262   9.9729    9.99281

8×24 Matrix{Float64}:
 4.5816    2.94373e-9  5.69652      …  5.3947       5.68318   5.79404
 0.549658  4.20699     2.34818e-10     6.7211       0.818163  3.73758
 0.433204  1.53035     1.89238         4.06066e-9   2.26868   3.65044
 5.03286   0.150425    6.3683          3.84675      6.02397   6.29072
 3.51923   6.63102     2.16923         5.80745      9.8566    4.51438
 0.651553  1.61213     4.70883      …  6.64697e-10  1.53437   3.65916
 3.49012   6.63686     2.03822         6.31412      8.22281   3.4513
 5.2876    3.23009     3.93032         1.59803      6.59904   3.02433

【Traffic Result】:Solve_Succeeded
n=9, iter_n=9, t=24 finish
------------------------------------------------
Academic license - for non-commercial use only
【Hydrogen Result】:Model was solved to optimality (subject to tolerances), and an optimal solution is available.
Solution is optimal
*********
n=9, iter_n=9
Error: 26.60502097425254
- error_ρⱼ: 0.02679766084763635
- error_pᵈ: 5.662011059972367
- error_λⱼ: 0.16740559121379306
- error_hydrogen_demand: 20.748806662218744
*********
*********
n=9, iter_n=9
Error: 0.00830778087673188
- relative error_ρⱼ: 1.397740867980444e-5
- relative error_pᵈ: 0.0067942179217348
- relative error_λⱼ: 5.714419053053207e-6
- relative error_hydrogen_demand: 0.0014938711272642227
*********
------------------------------------------------
n=10, iter_n=10, t=1 start
Academic license - for non-commercial use only
【Power Result】:Model was solved to optimality (subject to tolerances), and an optimal solution is available.
【Traffic Result】:Solve_Succeeded
n=10, ite

【Power Result】:Model was solved to optimality (subject to tolerances), and an optimal solution is available.
【Traffic Result】:Solve_Succeeded
n=10, iter_n=10, t=23 finish
------------------------------------------------
------------------------------------------------
n=10, iter_n=10, t=24 start
Academic license - for non-commercial use only
【Power Result】:Model was solved to optimality (subject to tolerances), and an optimal solution is available.

8×24 Matrix{Float64}:
  9.98016   9.97592   9.98008   9.99542  …   9.99641  10.0113    9.99442
  9.95184   9.95556   9.95193   9.95078      9.96721   9.96528   9.95071
  9.94937   9.95606   9.95162   9.94781      9.93707   9.94078   9.94886
  9.98975   9.98412   9.98937  10.0045      10.0209   10.0185   10.005
 10.015    10.0071   10.0149   10.0428      10.0626   10.0426   10.0246
  9.95401   9.95779   9.95409   9.94911  …   9.92977   9.93247   9.94904
 10.0143   10.0072   10.0121   10.0019      10.016    10.0079   10.002
  9.99516   9.99219   9.99494   9.9743       9.9731    9.97338   9.99294

8×24 Matrix{Float64}:
 4.5816    2.8359e-9  5.69652      …  5.3947       5.68318   5.79404
 0.549658  4.20699    2.26195e-10     6.7211       0.818163  3.73758
 0.433204  1.53035    1.89238         3.91149e-9   2.26868   3.65044
 5.03286   0.150425   6.3683          3.84675      6.02397   6.29072
 3.51923   6.63102    2.16923         5.80745      9.8566    4.51438
 0.651553  1.61213    4.70883      …  6.40281e-10  1.53437   3.65916
 3.49012   6.63686    2.03822         6.31412      8.22281   3.4513
 5.2876    3.23009    3.93032         1.59803      6.59904   3.02433


【Traffic Result】:Solve_Succeeded
n=10, iter_n=10, t=24 finish
------------------------------------------------
Academic license - for non-commercial use only
【Hydrogen Result】:Model was solved to optimality (subject to tolerances), and an optimal solution is available.
Solution is optimal
*********
n=10, iter_n=10
Error: 4.518336862230493
- error_ρⱼ: 0.01695595256646598
- error_pᵈ: 4.4170884773146835
- error_λⱼ: 0.08419340248087792
- error_hydrogen_demand: 9.902986846554995e-5
*********
*********
n=10, iter_n=10
Error: 0.005312078947054854
- relative error_ρⱼ: 8.844080884424745e-6
- relative error_pᵈ: 0.005300353776251109
- relative error_λⱼ: 2.8739599737918885e-6
- relative error_hydrogen_demand: 7.1299455283105096e-9
*********
Converged!
